name: "Set Branch Variables"
description: "Extract branch variables and export them as environment variables"
inputs:
  token:
    description: "GitHub token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Branch Variables
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        github_event_inputs_powpeg_branch: ${{ github.event.inputs.powpeg-branch }}
        github_event_inputs_rskj_branch: ${{ github.event.inputs.rskj-branch }}
        github_event_name: ${{ github.event_name }}
        github_event_pull_request_number: ${{ github.event.pull_request.number }}
        github_head_ref: ${{ github.head_ref }}
        github_ref_name: ${{ github.ref_name }}
      run: |
        PR_DESCRIPTION=pr-description.txt
        ALLOWED_BRANCH_CHARACTERS='[-+./0-9A-Z_a-z]'
        default_rskj_branch=master
        default_powpeg_branch=master
        default_rit_branch=main

        get_branch_from_description() {
          _prefix=$1
          _search_re='\@`'$_prefix:$ALLOWED_BRANCH_CHARACTERS'\{1,\}`@'
          _replace_re='s@.*`'$_prefix:'\('$ALLOWED_BRANCH_CHARACTERS'\{1,\}\)`.*@\1@p'
          _branch=$(sed -n "$_search_re $_replace_re" "$PR_DESCRIPTION")
          echo "$_branch"
        }

        is_valid_branch_name() {
          echo "$1" | grep -qx "$ALLOWED_BRANCH_CHARACTERS\\{1,\\}"
        }

        if [ "$github_event_name" = workflow_dispatch ]; then
          RSKJ_BRANCH=${github_event_inputs_rskj_branch:-$default_rit_branch}
          POWPEG_BRANCH=${github_event_inputs_powpeg_branch:-$default_powpeg_branch}
          RIT_BRANCH=$github_ref_name
        elif [ "$github_event_name" = pull_request ]; then
          gh pr view "$github_event_pull_request_number" --json body -q .body >"$PR_DESCRIPTION"
          RSKJ_BRANCH=$(get_branch_from_description rskj)
          : ${RSKJ_BRANCH:=$default_rskj_branch}
          POWPEG_BRANCH=$(get_branch_from_description fed)
          : ${POWPEG_BRANCH:=$default_powpeg_branch}
          RIT_BRANCH=$(get_branch_from_description rit)
          : ${RIT_BRANCH:=${github_head_ref:-$default_rskj_branch}}
        else
          RSKJ_BRANCH=$default_rskj_branch
          POWPEG_BRANCH=$default_powpeg_branch
          RIT_BRANCH=$default_rit_branch
        fi

        if ! is_valid_branch_name "$RSKJ_BRANCH"; then
          echo "rskj: invalid branch name: $RSKJ_BRANCH" >&2
          exit 1
        fi
        if ! is_valid_branch_name "$POWPEG_BRANCH"; then
          echo "fed: invalid branch name: $POWPEG_BRANCH" >&2
          exit 1
        fi
        if ! is_valid_branch_name "$RIT_BRANCH"; then
          echo "rit: invalid branch name: $RIT_BRANCH" >&2
          exit 1
        fi
        
        echo "RSKJ_BRANCH=$RSKJ_BRANCH" >> $GITHUB_ENV
        echo "RIT_BRANCH=$RIT_BRANCH" >> $GITHUB_ENV
        echo "POWPEG_BRANCH=$POWPEG_BRANCH" >> $GITHUB_ENV
