name: Build and Test

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
        RSKJ_BRANCH:
            description: 'The rskj branch to checkout'
            required: true
            default: 'master'
        FEDERATOR_BRANCH:
            description: 'The federate-node branch to checkout'
            required: true
            default: 'master'
        HSM_BRANCH:
            description: 'The hsm branch to checkout'
            required: true
            default: 'master'
        UTILITIES_BRANCH:
            description: 'The utilities branch to checkout'
            required: true
            default: 'master'
        RIT_BRANCH:
            description: 'The rootstock-integration-tests branch to checkout'
            required: true
            default: 'main'
        RIT_LOG_LEVEL:
            description: 'Log level for the rootstock-integration-tests'
            required: true
            default: 'info'

jobs:
  building-dependencies:
    runs-on: ubuntu-latest
    container:
      image: openjdk:8-jdk
    steps:
      - uses: actions/checkout@v4
      - name: Pull rskj
        run: |
          git clone https://github.com/rsksmart/rskj.git rskj
          cd rskj && git checkout ${{ github.event.inputs.RSKJ_BRANCH }}
          ./configure.sh && chmod +x gradlew
          ./gradlew --no-daemon clean build -x test

      - uses: actions/checkout@v4
      - name: Pull powpeg-node
        run: |
          git clone https://github.com/rsksmart/powpeg-node.git powpeg-node
          cd powpeg-node && git checkout ${{ github.event.inputs.FEDERATOR_BRANCH }}
          cp ../.github/scripts/configure_gradle_federator.sh .
          ./configure.sh && chmod +x ./gradlew && chmod +x configure_gradle_federator.sh
          ./configure_gradle_federator.sh
          ./gradlew --no-daemon clean build

      - uses: actions/checkout@v4
      - name: Pull hsm
        run: |
          git clone https://github.com/rootstock/hsm.git hsm
          cd hsm && git checkout ${{ github.event.inputs.HSM_BRANCH }}
      
  testing:
    needs: building-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Check Node.js version
        run: node --version
